// Référence CCAM dentaire v34 (liste officielle des actes bucco-dentaires).
// Généré depuis « liste actes ccam 34.pdf ». BR = base de remboursement Sécu (€), null si non prise en charge (NPC).
// Prothèses revalorisées : couronne/implanto 120 €, inlay-core 70 € (mise à jour convention 2026).
// poste = rattachement aux 6 postes de garantie de l app.

export type CcamPoste = 'soins' | 'prothese' | 'implant' | 'paro' | 'ortho' | 'esthetique'

export interface CcamActe { code: string; label: string; br: number | null; npc: boolean; poste: CcamPoste }

export const CCAM_ACTES: CcamActe[] = [
  { code: 'HBJD001', label: 'Détartrage et polissage des dents', br: 28.92, npc: false, poste: 'soins' },
  { code: 'HBBD005', label: 'Comblement [Scellement] prophylactique des puits, sillons et fissures sur une dent', br: 21.69, npc: false, poste: 'soins' },
  { code: 'HBBD006', label: 'Comblement [Scellement] prophylactique des puits, sillons et fissures sur 2 dents', br: 43.38, npc: false, poste: 'soins' },
  { code: 'HBBD007', label: 'Comblement [Scellement] prophylactique des puits, sillons et fissures sur 3 dents', br: 65.07, npc: false, poste: 'soins' },
  { code: 'HBBD004', label: 'Comblement [Scellement] prophylactique des puits, sillons et fissures sur 4 dents', br: 86.76, npc: false, poste: 'soins' },
  { code: 'HBBD039', label: 'Comblement [Scellement] prophylactique des puits, sillons et fissures sur 5 dents', br: 108.45, npc: false, poste: 'soins' },
  { code: 'HBBD404', label: 'Comblement [Scellement] prophylactique des puits, sillons et fissures sur 6 dents', br: 130.14, npc: false, poste: 'soins' },
  { code: 'HBBD098', label: 'Comblement [Scellement] prophylactique des puits, sillons et fissures sur 7 dents', br: 151.83, npc: false, poste: 'soins' },
  { code: 'HBBD427', label: 'Comblement [Scellement] prophylactique des puits, sillons et fissures sur 8 dents', br: 173.52, npc: false, poste: 'soins' },
  { code: 'HBLD004', label: 'Séance d\'application topique intrabuccale de fluorures', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD009', label: 'Application d’un topique pour hypersensibilité dentinaire', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD045', label: 'Application dentaire d’un vernis de reminéralisation sur une arcade Cosmétologie', br: null, npc: true, poste: 'soins' },
  { code: 'HBMD001', label: 'Séance d\'éclaircissement d’une dent dépulpée', br: null, npc: true, poste: 'esthetique' },
  { code: 'HBMD005', label: 'Séance d\'éclaircissement des dents pulpée SOINS CONSERVATEURS', br: null, npc: true, poste: 'esthetique' },
  { code: 'HBFD010', label: 'Parage de plaie de la pulpe d\'une dent avec coiffage', br: null, npc: true, poste: 'soins' },
  { code: 'HBMD043', label: 'Restauration d’une dent sur 1 face par matériau incrusté [inlay-onlay]', br: 19.28, npc: false, poste: 'prothese' },
  { code: 'HBMD046', label: 'Restauration d’une dent sur 2 faces par matériau incrusté [inlay-onlay]', br: 33.74, npc: false, poste: 'prothese' },
  { code: 'HBMD055', label: 'Restauration d’une dent sur 3 faces ou plus par matériau incrusté [inlay-onlay] Composites / amalgames', br: 40.97, npc: false, poste: 'prothese' },
  { code: 'HBMD058', label: 'Restauration d’une dent d’un secteur incisivocanin sur 1 face par matériau inséré en phase plastique, sans ancrage radiculaire', br: 19.28, npc: false, poste: 'soins' },
  { code: 'HBMD050', label: 'Restauration d’une dent d’un secteur incisivocanin sur 2 faces par matériau inséré en phase plastique sans ancrage radiculaire', br: 33.74, npc: false, poste: 'soins' },
  { code: 'HBMD054', label: 'Restauration d’une dent d’un secteur incisivocanin sur 3 faces ou plus par matériau inséré en phase plastique sans ancrage radiculaire', br: 40.97, npc: false, poste: 'soins' },
  { code: 'HBMD044', label: 'Restauration d\'une dent d’un secteur incisivocanin sur 1 angle par matériau inséré en phase plastique, sans ancrage radiculaire', br: 43, npc: false, poste: 'soins' },
  { code: 'HBMD047', label: 'Restauration d\'une dent d’un secteur incisivocanin sur 2 angles par matériau inséré en phase plastique, sans ancrage radiculaire', br: 86, npc: false, poste: 'soins' },
  { code: 'HBMD053', label: 'Restauration d’une dent d’un secteur prémolomolaire sur 1 face par matériau inséré en phase plastique, sans ancrage radiculaire', br: 19.28, npc: false, poste: 'soins' },
  { code: 'HBMD049', label: 'Restauration d’une dent d’un secteur prémolomolaire sur 2 faces par matériau inséré en phase plastique sans ancrage radiculaire', br: 33.74, npc: false, poste: 'soins' },
  { code: 'HBMD038', label: 'Restauration d’une dent d’un secteur prémolomolaire sur 3 faces ou plus par matériau inséré en phase plastique sans ancrage radiculaire', br: 40.97, npc: false, poste: 'soins' },
  { code: 'HBMD042', label: 'Restauration d\'une dent par matériau inséré en phase plastique avec ancrage radiculaire', br: 79.53, npc: false, poste: 'soins' },
  { code: 'HBMD006', label: 'Reconstitution coronaire provisoire pour acte endodontique sur dent délabrée', br: null, npc: true, poste: 'soins' },
  { code: 'HBFD006', label: 'Exérèse de la pulpe camérale (Biopulpotomie) d\'une dent temporaire (la pulpotomie d\'une dent définitive n\'existe pas dans la CCAM v34)', br: 16.87, npc: false, poste: 'soins' },
  { code: 'HBFD032', label: 'Exérèse partielle de la pulpe vivante d’une dent permanente immature pour apéxogénèse (pas apexification !)', br: null, npc: true, poste: 'soins' },
  { code: 'HBFD017', label: 'Exérèse de la pulpe vivante d’une incisive ou d’une canine temporaire', br: 33.74, npc: false, poste: 'soins' },
  { code: 'HBFD019', label: 'Exérèse de la pulpe vivante d’une molaire temporaire', br: 81.94, npc: false, poste: 'soins' },
  { code: 'HBFD033', label: 'Exérèse de la pulpe vivante d’une incisive ou d’une canine permanente', br: 33.74, npc: false, poste: 'soins' },
  { code: 'HBFD021', label: 'Exérèse de la pulpe vivante d’une première prémolaire maxillaire (permanente)', br: 48.2, npc: false, poste: 'soins' },
  { code: 'HBFD035', label: 'Exérèse de la pulpe vivante d’une prémolaire autre que la première prémolaire maxillaire (permanente)', br: 48.2, npc: false, poste: 'soins' },
  { code: 'HBFD008', label: 'Exérèse de la pulpe vivante d’une molaire permanente', br: 81.94, npc: false, poste: 'soins' },
  { code: 'HBFD015', label: 'Exérèse du contenu canalaire non vivant d\'une incisive ou canine temporaire', br: 33.74, npc: false, poste: 'soins' },
  { code: 'HBFD474', label: 'Exérèse du contenu canalaire non vivant d\'une molaire temporaire', br: 81.94, npc: false, poste: 'soins' },
  { code: 'HBFD001', label: 'Exérèse du contenu canalaire non vivant d’une incisive ou d’une canine permanente', br: 33.74, npc: false, poste: 'soins' },
  { code: 'HBFD458', label: 'Exérèse du contenu canalaire non vivant d\'une incisive ou d\'une canine permanente immature 33.74', br: null, npc: false, poste: 'soins' },
  { code: 'HBFD297', label: 'Exérèse du contenu canalaire non vivant d\'une première prémolaire maxillaire (permanente)', br: 48.2, npc: false, poste: 'soins' },
  { code: 'HBFD395', label: 'Exérèse du contenu canalaire non vivant d\'une première prémolaire maxillaire immature (permanente) 48.20', br: null, npc: false, poste: 'soins' },
  { code: 'HBFD003', label: 'Exérèse du contenu canalaire non vivant d’une prémolaire autre que la première prémolaire maxillaire (permanente)', br: 48.2, npc: false, poste: 'soins' },
  { code: 'HBFD326', label: 'Exérèse du contenu canalaire non vivant d\'une prémolaire immature autre que la première prémolaire maxillaire (permanente)', br: 48.2, npc: false, poste: 'soins' },
  { code: 'HBFD024', label: 'Exérèse du contenu canalaire non vivant d’une molaire permanente', br: 81.94, npc: false, poste: 'soins' },
  { code: 'HBFD150', label: 'Exérèse du contenu canalaire non vivant d\'une molaire permanente immature 81.94 Désobturations Les désobturations n\'incluent pas la mise en forme cana', br: null, npc: false, poste: 'soins' },
  { code: 'HBGD030', label: 'Désobturation endodontique d\'une incisive ou d\'une canine', br: null, npc: true, poste: 'soins' },
  { code: 'HBGD233', label: 'Désobturation endodontique d\'une première prémolaire maxillaire', br: null, npc: true, poste: 'soins' },
  { code: 'HBGD001', label: 'Désobturation endodontique d\'une prémolaire autre que la première prémolaire maxillaire', br: null, npc: true, poste: 'soins' },
  { code: 'HBGD033', label: 'Désobturation endodontique d\'une molaire', br: null, npc: true, poste: 'soins' },
  { code: 'HBGD012', label: 'Ablation d\'un corps étranger métallique d\'un canal radiculaire d\'une dent Apexification puis obturation L\'obturation radiculaire après apexification i', br: null, npc: true, poste: 'soins' },
  { code: 'HBBD003', label: 'Obturation radiculaire d\'une incisive ou d\'une canine après apexification', br: 33.74, npc: false, poste: 'soins' },
  { code: 'HBBD234', label: 'Obturation radiculaire d\'une première prémolaire maxillaire après apexification', br: 48.2, npc: false, poste: 'soins' },
  { code: 'HBBD001', label: 'Obturation radiculaire d\'une prémolaire autre que la première prémolaire maxillaire après apexification', br: 48.2, npc: false, poste: 'soins' },
  { code: 'HBBD002', label: 'Obturation radiculaire d\'une molaire après apexification Autres actes d\'endodontie', br: 81.94, npc: false, poste: 'soins' },
  { code: 'HBMD003', label: 'Séance de renouvellement de l\'obturation radiculaire d\'une dent permanente immature à l\'hydroxyde de calcium (attention, la première séance d\'applicat', br: null, npc: true, poste: 'soins' },
  { code: 'HBBA001', label: 'Obturation d’une résorption radiculaire dentaire externe, par abord parodontal', br: null, npc: true, poste: 'paro' },
  { code: 'HBGD035', label: 'DC8Avulsion d\'une dent temporaire sur arcade', br: 16.72, npc: false, poste: 'soins' },
  { code: 'HBGD037', label: 'DC12Avulsion de 2 dents temporaires sur arcade', br: 25.08, npc: false, poste: 'soins' },
  { code: 'HBGD309', label: 'DC16Avulsion de 3 dents temporaires sur arcade', br: 33.44, npc: false, poste: 'soins' },
  { code: 'HBGD284', label: 'DC20Avulsion de 4 dents temporaires sur arcade', br: 41.8, npc: false, poste: 'soins' },
  { code: 'HBGD065', label: 'DC24Avulsion de 5 dents temporaires sur arcade', br: 50.16, npc: false, poste: 'soins' },
  { code: 'HBGD462', label: 'DC28Avulsion de 6 dents temporaires sur arcade', br: 58.52, npc: false, poste: 'soins' },
  { code: 'HBGD464', label: 'DC32Avulsion de 7 dents temporaires sur arcade', br: 66.88, npc: false, poste: 'soins' },
  { code: 'HBGD263', label: 'DC36Avulsion de 8 dents temporaires sur arcade', br: 75.24, npc: false, poste: 'soins' },
  { code: 'HBGD280', label: 'DC40Avulsion de 9 dents temporaires sur arcade', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD093', label: 'DC44Avulsion de 10 dents temporaires sur arcade', br: 91.96, npc: false, poste: 'soins' },
  { code: 'HBGD362', label: 'DC48Avulsion de 11 dents temporaires sur arcade', br: 100.32, npc: false, poste: 'soins' },
  { code: 'HBGD054', label: 'DC52Avulsion de 12 dents temporaires sur arcade', br: 108.67, npc: false, poste: 'soins' },
  { code: 'HBGD111', label: 'DC56Avulsion de 13 dents temporaires sur arcade', br: 117.04, npc: false, poste: 'soins' },
  { code: 'HBGD174', label: 'DC60Avulsion de 14 dents temporaires sur arcade', br: 125.4, npc: false, poste: 'soins' },
  { code: 'HBGD057', label: 'DC64Avulsion de 15 dents temporaires sur arcade', br: 133.76, npc: false, poste: 'soins' },
  { code: 'HBGD133', label: 'DC68Avulsion de 16 dents temporaires sur arcade', br: 142.12, npc: false, poste: 'soins' },
  { code: 'HBGD123', label: 'DC72Avulsion de 17 dents temporaires sur arcade', br: 150.48, npc: false, poste: 'soins' },
  { code: 'HBGD468', label: 'DC76Avulsion de 18 dents temporaires sur arcade', br: 158.84, npc: false, poste: 'soins' },
  { code: 'HBGD282', label: 'DC80Avulsion de 19 dents temporaires sur arcade', br: 167.2, npc: false, poste: 'soins' },
  { code: 'HBGD201', label: 'DC84Avulsion de 20 dents temporaires sur arcade', br: 175.56, npc: false, poste: 'soins' },
  { code: 'HBGD042', label: 'DC40Avulsion de 1 dent temporaire retenue, incluse ou réincluse', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD026', label: 'DC60Avulsion de 2 dents temporaires incluses, retenues ou réincluses Extractions de dents permanentes', br: 125.4, npc: false, poste: 'soins' },
  { code: 'HBGD036', label: 'DC16Avulsion d\'1 dent permanente sur arcade sans alvéolectomie', br: 33.44, npc: false, poste: 'soins' },
  { code: 'HBGD043', label: 'DC24Avulsion de 2 dents permanentes sur arcade sans alvéolectomie', br: 50.16, npc: false, poste: 'soins' },
  { code: 'HBGD319', label: 'DC32Avulsion de 3 dents permanentes sur arcade sans alvéolectomie', br: 66.88, npc: false, poste: 'soins' },
  { code: 'HBGD489', label: 'DC40Avulsion de 4 dents permanentes sur arcade sans alvéolectomie', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD497', label: 'DC48Avulsion de 5 dents permanentes sur arcade sans alvéolectomie', br: 100.32, npc: false, poste: 'soins' },
  { code: 'HBGD106', label: 'DC56Avulsion de 6 dents permanentes sur arcade sans alvéolectomie', br: 117.04, npc: false, poste: 'soins' },
  { code: 'HBGD076', label: 'DC64Avulsion de 7 dents permanentes sur arcade sans alvéolectomie', br: 133.76, npc: false, poste: 'soins' },
  { code: 'HBGD422', label: 'DC72Avulsion de 8 dents permanentes sur arcade sans alvéolectomie', br: 150.48, npc: false, poste: 'soins' },
  { code: 'HBGD420', label: 'DC80Avulsion de9 dents permanentes sur arcade sans alvéolectomie', br: 167.2, npc: false, poste: 'soins' },
  { code: 'HBGD064', label: 'DC88Avulsion de 10 dents permanentes sur arcade sans alvéolectomie', br: 183.92, npc: false, poste: 'soins' },
  { code: 'HBGD356', label: 'DC96Avulsion de 11 dents permanentes sur arcade sans alvéolectomie', br: 200.64, npc: false, poste: 'soins' },
  { code: 'HBGD146', label: 'DC104Avulsion de 12 dents permanentes sur arcade sans alvéolectomie', br: 217.36, npc: false, poste: 'soins' },
  { code: 'HBGD382', label: 'DC112Avulsion de 13 dents permanentes sur arcade sans alvéolectomie', br: 234.08, npc: false, poste: 'soins' },
  { code: 'HBGD247', label: 'DC120Avulsion de 14 dents permanentes sur arcade sans alvéolectomie', br: 250.8, npc: false, poste: 'soins' },
  { code: 'HBGD197', label: 'DC128Avulsion de 15 dents permanentes sur arcade sans alvéolectomie', br: 267.52, npc: false, poste: 'soins' },
  { code: 'HBGD333', label: 'DC136Avulsion de 16 dents permanentes sur arcade sans alvéolectomie', br: 284.24, npc: false, poste: 'soins' },
  { code: 'HBGD261', label: 'DC144Avulsion de 17 dents permanentes sur arcade sans alvéolectomie', br: 300.96, npc: false, poste: 'soins' },
  { code: 'HBGD499', label: 'DC152Avulsion de 18 dents permanentes sur arcade sans alvéolectomie', br: 317.68, npc: false, poste: 'soins' },
  { code: 'HBGD461', label: 'DC160Avulsion de 19 dents permanentes sur arcade sans alvéolectomie', br: 334.4, npc: false, poste: 'soins' },
  { code: 'HBGD278', label: 'DC168Avulsion de 20 dents permanentes sur arcade sans alvéolectomie', br: 351.12, npc: false, poste: 'soins' },
  { code: 'HBGD258', label: 'DC176Avulsion de 21 dents permanentes sur arcade sans alvéolectomie', br: 367.84, npc: false, poste: 'soins' },
  { code: 'HBGD311', label: 'DC184Avulsion de 22 dents permanentes sur arcade sans alvéolectomie', br: 384.56, npc: false, poste: 'soins' },
  { code: 'HBGD235', label: 'DC192Avulsion de 23 dents permanentes sur arcade sans alvéolectomie', br: 401.28, npc: false, poste: 'soins' },
  { code: 'HBGD374', label: 'DC200Avulsion de 24 dents permanentes sur arcade sans alvéolectomie', br: 418, npc: false, poste: 'soins' },
  { code: 'HBGD475', label: 'DC208Avulsion de 25 dents permanentes sur arcade sans alvéolectomie', br: 434.72, npc: false, poste: 'soins' },
  { code: 'HBGD285', label: 'DC216Avulsion de 26 dents permanentes sur arcade sans alvéolectomie', br: 451.44, npc: false, poste: 'soins' },
  { code: 'HBGD338', label: 'DC224Avulsion de 27 dents permanentes sur arcade sans alvéolectomie', br: 468.16, npc: false, poste: 'soins' },
  { code: 'HBGD193', label: 'DC232Avulsion de 28 dents permanentes sur arcade sans alvéolectomie', br: 484.88, npc: false, poste: 'soins' },
  { code: 'HBGD345', label: 'DC240Avulsion de 29 dents permanentes sur arcade sans alvéolectomie', br: 501.6, npc: false, poste: 'soins' },
  { code: 'HBGD414', label: 'DC248Avulsion de 30 dents permanentes sur arcade sans alvéolectomie', br: 518.32, npc: false, poste: 'soins' },
  { code: 'HBGD245', label: 'DC256Avulsion de 31 dents permanentes sur arcade sans alvéolectomie', br: 535.04, npc: false, poste: 'soins' },
  { code: 'HBGD283', label: 'DC264Avulsion de 32 dents permanentes sur arcade sans alvéolectomie', br: 551.76, npc: false, poste: 'soins' },
  { code: 'HBGD022', label: 'DC16Avulsion d\'1 dent permanente sur arcade avec alvéolectomie', br: 33.44, npc: false, poste: 'soins' },
  { code: 'HBGD034', label: 'DC24Avulsion de 2 dents permanentes sur arcade avec alvéolectomie', br: 50.16, npc: false, poste: 'soins' },
  { code: 'HBGD287', label: 'DC32Avulsion de 3 dents permanentes sur arcade avec alvéolectomie', br: 66.88, npc: false, poste: 'soins' },
  { code: 'HBGD031', label: 'DC16Avulsion d\'une dent permanente sur arcade avec séparation des racines', br: 33.44, npc: false, poste: 'soins' },
  { code: 'HBGD032', label: 'DC24Avulsion de 2 dents permanentes sur arcade avec séparation des racines', br: 50.16, npc: false, poste: 'soins' },
  { code: 'HBGD039', label: 'DC16Avulsion d\'1 dent ankylosée sur arcade, avec section coronoradiculaire et séparation des racines', br: 33.44, npc: false, poste: 'soins' },
  { code: 'HBGD002', label: 'DC24Avulsion de 2 dents ankylosées sur arcade, avec section coronoradiculaire et séparation des racines', br: 50.16, npc: false, poste: 'soins' },
  { code: 'HBGD028', label: 'DC40Avulsion d\'une incisive permanente retenue ou à l\'état de germe', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD014', label: 'DC50Avulsion d\'une canine permanente retenue ou à l\'état de germe', br: 104.5, npc: false, poste: 'soins' },
  { code: 'HBGD015', label: 'DC50 + DC25Avulsion de 2 canines permanentes retenues ou à l\'état de germe', br: 156.75, npc: false, poste: 'soins' },
  { code: 'HBGD459', label: 'DC40Avulsion d\'1 prémolaire retenue ou à l\'état de germe', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD386', label: 'DC60Avulsion de 2 prémolaires retenues ou à l\'état de germe', br: 125.4, npc: false, poste: 'soins' },
  { code: 'HBGD047', label: 'DC40Avulsion d\'une première ou d\'une deuxième molaire permanente retenue ou à l\'état de germe', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD018', label: 'DC40Avulsion d\'une troisième molaire maxillaire retenue ou à l\'état de germe', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD004', label: 'DC40Avulsion d\'une troisième molaire mandibulaire retenue ou à l\'état de germe', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD025', label: 'DC40+DC20Avulsion de 2 troisièmes molaires retenues ou à l\'état de germe', br: 125.4, npc: false, poste: 'soins' },
  { code: 'HBGD021', label: 'DC40+2DC20Avulsion de 3 troisièmes molaires mandibulaires retenues ou à l\'état de germe', br: 167.2, npc: false, poste: 'soins' },
  { code: 'HBGD038', label: 'DC40+3DC20Avulsion de 4 troisièmes molaires retenues ou à l\'état de germe', br: 209, npc: false, poste: 'soins' },
  { code: 'HBGD044', label: 'DC20Avulsion d\'une dent à couronne sousmuqueuse ou en désinclusion muqueuse', br: 41.8, npc: false, poste: 'soins' },
  { code: 'HBGD003', label: 'DC40Avulsion d\'un odontoïde inclus ou d\'une dent surnuméraire à l\'état de germe', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD016', label: 'DC40Avulsion d\'une racine incluse', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HBGD017', label: 'DC80Avulsion d\'une dent ectopique', br: 167.2, npc: false, poste: 'soins' },
  { code: 'HBGD040', label: 'DC40+20...Avulsion de plusieurs dents surnuméraires à l\'état de germe ou de plusieurs odontoïdes (avec ou sans régularisation de crête)', br: 125.4, npc: false, poste: 'soins' },
  { code: 'HBFD014', label: 'Amputation et/ou séparation radiculaire ou coronoradiculaire d\'une dent', br: null, npc: true, poste: 'paro' },
  { code: 'HBED011', label: 'Réduction de luxation d\'une dent', br: null, npc: true, poste: 'soins' },
  { code: 'HBED016', label: 'Réduction de luxation de plusieurs dents', br: null, npc: true, poste: 'soins' },
  { code: 'HBED009', label: 'Réduction de fracture alvéolaire en denture permanente', br: 104.5, npc: false, poste: 'soins' },
  { code: 'HBED015', label: 'Réduction de fracture alvéolaire en denture mixte ou incomplète', br: 104.5, npc: false, poste: 'implant' },
  { code: 'HBED001', label: 'Réimplantation d\'une dent permanente expulsée', br: 96.4, npc: false, poste: 'implant' },
  { code: 'HBED003', label: 'Réimplantation de 2 dents permanentes expulsées', br: 192.8, npc: false, poste: 'implant' },
  { code: 'HBED021', label: 'Réimplantation de 3 dents permanentes expulsées, ou plus', br: 289.2, npc: false, poste: 'implant' },
  { code: 'HBED022', label: 'DC100Autogreffe d\'un germe ou d\'une dent retenue, dans un site naturel ou préparé chirurgicalement', br: 209, npc: false, poste: 'soins' },
  { code: 'HBED005', label: 'Autogreffe d\'une dent sur arcade, dans un site naturel ou préparé chirurgicalement Dégagement de dent retenue ou incluse', br: null, npc: true, poste: 'soins' },
  { code: 'HBPD002', label: 'Dégagement d\'une dent retenue ou incluse avec pose d\'un dispositif de traction orthodontique sans aménagement parodontal', br: 104.5, npc: false, poste: 'ortho' },
  { code: 'HBPA001', label: 'Dégagement d\'une dent retenue ou incluse, avec pose d\'un dispositif de traction orthodontique et aménagement parodontal par greffe ou lambeau', br: 146.3, npc: false, poste: 'ortho' },
  { code: 'HBPD001', label: 'Dégagement de plusieurs dents retenues ou incluses avec pose de dispositif de traction orthodontique Évacuations de collections', br: 156.75, npc: false, poste: 'ortho' },
  { code: 'LCJA004', label: 'Évacuation de collection de la région des muscles masticateurs, par abord intrabuccal', br: 83.6, npc: false, poste: 'soins' },
  { code: 'LCJA002', label: 'Évacuation de collection de la région des muscles masticateurs, par abord intrabuccal et par abord facial', br: 83.6, npc: false, poste: 'soins' },
  { code: 'LCJA003', label: 'Évacuation de collection périmaxillaire ou périmandibulaire, par abord intrabuccal', br: 20.9, npc: false, poste: 'soins' },
  { code: 'HAJA002', label: 'Évacuation de collection pelvilinguale, par abord intrabuccal', br: 41.8, npc: false, poste: 'soins' },
  { code: 'HAJD004', label: 'Évacuation de collection de la base de la langue Traitement de plaie intrabuccale', br: 83.6, npc: false, poste: 'soins' },
  { code: 'HAJA010', label: 'Parage et/ou suture d\'une plaie muqueuse intrabuccale', br: 23.3, npc: false, poste: 'soins' },
  { code: 'HAJA007', label: 'Parage et/ou suture de plaies muqueuses intrabuccales multiples', br: 32.49, npc: false, poste: 'soins' },
  { code: 'HAJA009', label: 'Parage et/ou suture de plaie de la langue', br: 28.5, npc: false, poste: 'soins' },
  { code: 'HAJA008', label: 'Parage et/ou suture de plaie du voile du palais [A, F, P, S, U, I, X]', br: 36.51, npc: false, poste: 'soins' },
  { code: 'HASD003', label: 'Hémostase secondaire à une électrocoagulation intrabuccale', br: 36.44, npc: false, poste: 'soins' },
  { code: 'HBSD001', label: 'Hémostase gingivoalvéolaire secondaire à une avulsion dentaire (ne peut pas être facturé dans la séance d\'avulsion dentaire) Traitement des lésions', br: 22.05, npc: false, poste: 'soins' },
  { code: 'HAND002', label: 'Destruction de lésion de la muqueuse de la bouche ou de l\'oropharynx de moins de 2 cm de grand axe, par voie buccale sans laser', br: 22.13, npc: false, poste: 'soins' },
  { code: 'HAND004', label: 'Destruction de lésion de la muqueuse de la bouche ou de l\'oropharynx de moins de 2 cm de grand axe, par voie buccale avec laser', br: 22.2, npc: false, poste: 'soins' },
  { code: 'HAND001', label: 'Destruction de lésion de la muqueuse de la bouche ou de l\'oropharynx de 2 cm à 4 cm de grand axe, par voie buccale sans laser', br: 29.94, npc: false, poste: 'soins' },
  { code: 'HAND006', label: 'Destruction de lésion de la muqueuse de la bouche ou de l\'oropharynx de 2 cm à 4 cm de grand axe, par voie buccale avec laser', br: 30.04, npc: false, poste: 'soins' },
  { code: 'HAFA015', label: 'Exérèse de lésion de la muqueuse de la bouche ou de l\'oropharynx de moins de 2 cm de grand axe, par abord intrabuccal', br: 37.01, npc: false, poste: 'soins' },
  { code: 'HAFA032', label: 'Exérèse de lésion de la muqueuse de la bouche ou de l\'oropharynx de 2 cm à 4 cm de grand axe, par abord intrabuccal', br: 104.5, npc: false, poste: 'soins' },
  { code: 'LBFA023', label: 'Exérèse de lésion de l\'os maxillaire et/ou du corps de la mandibule de moins de 2 cm de grand axe, par abord intrabuccal Comprend ou non une avulsion', br: 46.89, npc: false, poste: 'soins' },
  { code: 'HBQK389', label: 'Radiographie intrabuccale rétroalvéolaire et/ou rétrocoronaire d\'un secteur de 1 à 3 dents contigües', br: 7.98, npc: false, poste: 'soins' },
  { code: 'HBQK191', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 2 secteurs distincts de 1 à 3 dents contigües', br: 15.96, npc: false, poste: 'soins' },
  { code: 'HBQK331', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 3 secteurs distincts de 1 à 3 dents contigües', br: 23.94, npc: false, poste: 'soins' },
  { code: 'HBQK443', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 4 secteurs distincts de 1 à 3 dents contigües', br: 31.92, npc: false, poste: 'soins' },
  { code: 'HBQK428', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 5 secteurs distincts de 1 à 3 dents contigües', br: 39.9, npc: false, poste: 'soins' },
  { code: 'HBQK480', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 6 secteurs distincts de 1 à 3 dents contigües', br: 47.88, npc: false, poste: 'soins' },
  { code: 'HBQK430', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 7 secteurs distincts de 1 à 3 dents contigües', br: 55.86, npc: false, poste: 'soins' },
  { code: 'HBQK142', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 8 secteurs distincts de 1 à 3 dents contigües', br: 63.84, npc: false, poste: 'soins' },
  { code: 'HBQK046', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 9 secteurs distincts de 1 à 3 dents contigües', br: 71.82, npc: false, poste: 'soins' },
  { code: 'HBQK065', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 10 secteurs distincts de 1 à 3 dents contigües', br: 79.8, npc: false, poste: 'soins' },
  { code: 'HBQK424', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 11 secteurs distincts de 1 à 3 dents contigües', br: 87.78, npc: false, poste: 'soins' },
  { code: 'HBQK476', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 12 secteurs distincts de 1 à 3 dents contigües', br: 95.76, npc: false, poste: 'soins' },
  { code: 'HBQK093', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 13 secteurs distincts de 1 à 3 dents contigües', br: 103.74, npc: false, poste: 'soins' },
  { code: 'HBQK041', label: 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 14 secteurs distincts de 1 à 3 dents contigües', br: 111.72, npc: false, poste: 'soins' },
  { code: 'HBQK002', label: 'Radiographie panoramique dentomaxillaire', br: 21.28, npc: false, poste: 'soins' },
  { code: 'HBQK001', label: 'Radiographie pelvibuccale [occlusale] Rétroalvéolaires perinterventionnelles Pour l\'ENDODONTIE les cotations de radiographies sont sont des forfaits q', br: 7.98, npc: false, poste: 'soins' },
  { code: 'HBQK040', label: '+Z3Radiographies intrabuccales rétroalvéolaires sur un secteur de 1 à 3 dents contigues préinterventionnelle ou périinterventionnelle avec radiographi', br: 11.97, npc: false, poste: 'soins' },
  { code: 'HBQK303', label: '+Z3+Z3Radiographies intrabuccales rétroalvéolaires sur un secteur de 1 à 3 dents contigues préinterventionnelle et périinterventionnelle avec radiogra', br: 15.96, npc: false, poste: 'soins' },
  { code: 'HBQK061', label: 'Radiographie intrabuccale rétroalvéolaire et/ou rétrocoronaire d\'un secteur de 1 à 3 dents contigues, perinterventionnelle et/ou finale en dehors d\'un', br: 3.99, npc: false, poste: 'soins' },
  { code: 'LAQK003', label: 'Radiographie du crâne et/ou massif facial selon 1 ou 2 incidences [E,F,P,S,U, Y,Z] Radiographie des sinus paranasaux, du maxillaire défilé, des os pro', br: 23.94, npc: false, poste: 'soins' },
  { code: 'LAQK005', label: 'Radiographie du crâne selon 3 incidences', br: 34.58, npc: false, poste: 'soins' },
  { code: 'LBQK005', label: 'Radiographie unilatérale ou bilatérale de l\'ATM Radiographie selon l\'incidence de Zimmer [E, F, P, S, U, Y, Z]', br: 25.27, npc: false, poste: 'soins' },
  { code: 'LAQK012', label: 'Téléradiographie du crâne et du massif facial selon 1 incidence Pour diagnostic orthodontique', br: 19.95, npc: false, poste: 'ortho' },
  { code: 'LAQK001', label: 'Téléradiographie du crâne et du massif facial selon 2 incidences Pour diagnostic orthodontique', br: 26.6, npc: false, poste: 'ortho' },
  { code: 'LAQK008', label: 'Téléradiographie du crâne et du massif facial selon 3 incidences Pour diagnostic orthodontique', br: 26.6, npc: false, poste: 'ortho' },
  { code: 'LBQK001', label: 'Tomographie unilatérale ou bilatérale de l\'ATM', br: 46.55, npc: false, poste: 'soins' },
  { code: 'LBQH001', label: 'Arthrographie unilatérale de l\'ATM [E, Y, Z]', br: 57.19, npc: false, poste: 'soins' },
  { code: 'LBQH003', label: 'Arthrographie bilatérale de l\'ATM', br: 114.38, npc: false, poste: 'soins' },
  { code: 'LAQK002', label: 'Scanographie unilatérale ou bilatérale de la partie pétreuse de l\'os temporal (rocher) et de l\'oreille moyenne [E, F, P, S, U, Z]', br: 25.27, npc: false, poste: 'soins' },
  { code: 'LAQK011', label: 'Scanographie unilatérale ou bilatérale de l\'angle pontocérébelleux et/ou du méat acoustique interne (conduit auditif interne) [E, Z]', br: 25.27, npc: false, poste: 'soins' },
  { code: 'LAQK013', label: 'Scanographie de la face (Dentascanner)', br: 25.27, npc: false, poste: 'implant' },
  { code: 'LAQK009', label: 'Scanographie de la face avec scanographie des tissus mous du cou [E, F, P, S, U,Z]', br: 25.27, npc: false, poste: 'soins' },
  { code: 'LBQH002', label: 'Arthroscanographie unilatérale ou bilatérale de l\'ATM [E, Y, Z]', br: 57.19, npc: false, poste: 'soins' },
  { code: 'LAQK027', label: 'Radiographie volumique par faisceau conique [cone beam computerized tomography][CBCT] du maxillaire, de la mandibule et/ou d\'arcade dentaire Ne peut p', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD006', label: 'Pose d’un mainteneur d’espace interdentaire unitaire scellé À l\'exclusion de : pose d\'un arc de maintien d\'espace interdentaire (HBLD001, HBLD003)', br: null, npc: true, poste: 'ortho' },
  { code: 'HBLD002', label: 'Pose d’un mainteneur d’espace interdentaire amovible passif', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD001', label: 'Pose d’un arc de maintien d’espace interdentaire sans dent prothétique', br: null, npc: true, poste: 'ortho' },
  { code: 'HBLD003', label: 'Pose d’un arc de maintien d’espace interdentaire avec dent prothétique Orthèses et Gouttières', br: null, npc: true, poste: 'ortho' },
  { code: 'HALD002', label: 'Pose d\'un appareillage antiautomorsure', br: null, npc: true, poste: 'soins' },
  { code: 'HALD004', label: 'Pose d\'une plaque palatine non active [passive] pour fente orofaciale ou division palatine', br: 48, npc: false, poste: 'soins' },
  { code: 'HALD003', label: 'Pose d\'une plaque palatine active [orthopédique] pour fente orofaciale', br: 48, npc: false, poste: 'soins' },
  { code: 'LBLD017', label: 'Pose d’un appareillage en propulsion mandibulaire (Activateur mandibulaire)', br: null, npc: true, poste: 'soins' },
  { code: 'LBLD007', label: 'Pose d’un appareillage de protection dentomaxillaire (Protège dents)', br: null, npc: true, poste: 'soins' },
  { code: 'LBLD014', label: 'Pose d’une orthèse métallique recouvrant totalement ou partiellement une arcade dentaire', br: 172.8, npc: false, poste: 'soins' },
  { code: 'LBLD011', label: 'Pose d\'un appareillage par guide mandibulaire, vestibulaire ou lingual, sur 1 arcade', br: 84.48, npc: false, poste: 'soins' },
  { code: 'LBLD009', label: 'Pose d\'un appareillage par guide mandibulaire, vestibulaire ou lingual, sur 2 arcades', br: 153.6, npc: false, poste: 'soins' },
  { code: 'LBLD018', label: 'Pose d’un appareillage par guide mandibulaire sagittal', br: 153.6, npc: false, poste: 'soins' },
  { code: 'LBLD003', label: 'Pose d’une gouttière maxillaire ou mandibulaire pour hémostase ou portetopique', br: 86.4, npc: false, poste: 'soins' },
  { code: 'LBLD006', label: 'Pose de gouttières maxillaire et mandibulaire pour hémostase ou portetopique', br: 172.8, npc: false, poste: 'soins' },
  { code: 'LBLD022', label: 'Pose de gouttière plombée de protection dento-osseuse (Gouttière protection radio) Occlusodontie', br: 153.6, npc: false, poste: 'soins' },
  { code: 'HBMD061', label: 'Séance d\'ajustement occlusal par coronoplastie', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD020', label: 'Pose d\'un appareil de posture mandibulaire (cale mandibulaire)', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD018', label: 'Pose d\'un plan de libération occlusale (plan de désocclusion)', br: 172.8, npc: false, poste: 'soins' },
  { code: 'HBLD019', label: 'Pose d\'un plan de guidage des mouvements antéropostérieurs mandibulaires Epreuves fonctionnelles', br: null, npc: true, poste: 'soins' },
  { code: 'LBMP003', label: 'Réalisation de moulage d\'étude des arcades dentaires', br: null, npc: true, poste: 'soins' },
  { code: 'LBQP001', label: 'Enregistrement des rapports maxillomandibulaires en vue de la programmation d\'un articulateur', br: null, npc: true, poste: 'implant' },
  { code: 'LBMP001', label: 'Simulation des objectifs thérapeutiques sur moulages des arcades dentaires et/ou sur logiciel À l\'exclusion de : enregistrement des rapports maxilloma', br: null, npc: true, poste: 'implant' },
  { code: 'LBMP002', label: 'Montage directeur sur moulage d\'étude des arcades dentaires', br: null, npc: true, poste: 'soins' },
  { code: 'HBMD014', label: 'Modélisation occlusale par la technique de la cire ajoutée sur une dent Prothèses conjointes Poses Inlay cores sur dents', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD007', label: 'Pose d\'une infrastructure coronoradiculaire sans clavette sur une dent [Inlay core]', br: 70, npc: false, poste: 'prothese' },
  { code: 'HBLD261', label: 'Pose d\'une infrastructure coronoradiculaire avec clavette sur une dent [Inlay core à clavette]', br: 70, npc: false, poste: 'prothese' },
  { code: 'HBLD015', label: 'Pose d\'une coiffe de recouvrement d\'une racine dentaire [Coping] Couronnes unitaires Couronne dentaire fixée dentoportée quand la dent ne peut être re', br: null, npc: true, poste: 'prothese' },
  { code: 'HBLD037', label: 'Pose d\'une couronne dentaire transitoire', br: null, npc: true, poste: 'prothese' },
  { code: 'HBLD038', label: 'Pose d\'une couronne dentaire métallique', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD036', label: 'Pose d\'une couronne dentaire céramométallique ou en équivalents minéraux (notamment CCM, CIV)', br: 120, npc: false, poste: 'prothese' },
  // --- Couronnes par PANIER (réforme 100 % Santé 2020, absentes du PDF v34 — source aideaucodage.fr) ---
  { code: 'HBLD634', label: 'Pose d\'une couronne dentaire dentoportée céramométallique sur incisive, canine ou 1re prémolaire (100 % Santé)', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD491', label: 'Pose d\'une couronne dentaire dentoportée céramométallique sur 2e prémolaire (tarif maîtrisé)', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD734', label: 'Pose d\'une couronne dentaire dentoportée céramométallique sur molaire (tarif maîtrisé)', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD073', label: 'Pose d\'une couronne dentaire dentoportée en zircone monolithique sur molaire (100 % Santé)', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD350', label: 'Pose d\'une couronne dentaire dentoportée en zircone monolithique (100 % Santé)', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD680', label: 'Pose d\'une couronne dentaire dentoportée en céramique monolithique hors zircone sur incisive, canine ou 1re prémolaire (100 % Santé)', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD158', label: 'Pose d\'une couronne dentaire dentoportée en céramique monolithique hors zircone sur 2e prémolaire ou molaire (tarif maîtrisé)', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD403', label: 'Pose d\'une couronne dentaire dentoportée céramocéramique (tarif libre)', br: 120, npc: false, poste: 'prothese' },
  { code: 'HBLD318', label: 'Pose d\'une couronne dentaire dentoportée métallique en alliage précieux (tarif libre)', br: 120, npc: false, poste: 'prothese' },
  // Inlay-core par panier (BR 70 € convention 2026)
  { code: 'HBLD090', label: 'Pose d\'une infrastructure coronoradiculaire [inlay-core] (panier 100 % Santé / maîtrisé)', br: 70, npc: false, poste: 'prothese' },
  { code: 'HBLD245', label: 'Pose d\'une infrastructure coronoradiculaire [inlay-core] (tarif libre)', br: 70, npc: false, poste: 'prothese' },
  { code: 'HBLD745', label: 'Pose d\'une infrastructure coronoradiculaire [inlay-core]', br: 70, npc: false, poste: 'prothese' },
  { code: 'HBMD048', label: 'Pose d\'une facette céramique ou en équivalents minéraux sur une dent d’un secteur incisivocanin', br: null, npc: true, poste: 'esthetique' },
  { code: 'HBLD418', label: 'Couronne implantoportée Bridge (prothèse plurale)', br: 120, npc: false, poste: 'implant' },
  { code: 'HBLD034', label: 'Pose d’une prothèse dentaire plurale transitoire', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD040', label: 'Pose d\'une prothèse plurale [bridge] comportant 1 pilier d\'ancrage métallique, 1 pilier d\'ancrage céramométallique ou en équivalents minéraux, et 1 él', br: 279.5, npc: false, poste: 'prothese' },
  { code: 'HBLD043', label: 'Pose d\'une prothèse plurale [bridge] comportant 1 pilier d\'ancrage métallique, 1 pilier d\'ancrage céramométallique ou en équivalents minéraux, et 1 él', br: 279.5, npc: false, poste: 'prothese' },
  { code: 'HBLD033', label: 'Pose d\'une prothèse plurale [bridge] comportant 2 piliers d\'ancrage métalliques et 1 élément intermédiaire métallique', br: 279.5, npc: false, poste: 'prothese' },
  { code: 'HBLD023', label: 'Pose d\'une prothèse plurale [bridge] comportant 2 piliers d\'ancrage céramométalliques ou en équivalents minéraux et 1 élément intermédiaire céramométa', br: 279.5, npc: false, poste: 'prothese' },
  { code: 'HBMD490', label: 'Adjonction d\'un 1er élément intermédiaire métallique à une prothèse dentaire plurale fixée [2e élément métallique intermédiaire de bridge]', br: null, npc: true, poste: 'prothese' },
  { code: 'HBMD342', label: 'Adjonction d\'un 2e élément intermédiaire métallique à une prothèse dentaire plurale [3e élément métallique intermédiaire de bridge]', br: null, npc: true, poste: 'prothese' },
  { code: 'HBMD082', label: 'Adjonction à une prothèse dentaire plurale fixée d\'un élément intermédiaire métallique supplémentaire, au-delà du 3e', br: 10.75, npc: false, poste: 'soins' },
  { code: 'HBMD479', label: 'Adjonction d\'un 1er élément intermédiaire céramométallique ou en équivalents minéraux à une prothèse dentaire plurale fixée [2e élément céramométalliq', br: null, npc: true, poste: 'prothese' },
  { code: 'HBMD433', label: 'Adjonction d\'un 2e élément intermédiaire céramométallique ou en équivalents minéraux à une prothèse dentaire plurale fixée [3e élément céramométalliqu', br: null, npc: true, poste: 'prothese' },
  { code: 'HBMD072', label: 'Adjonction à une prothèse dentaire plurale fixée d\'un élément intermédiaire céramométallique ou en équivalents minéraux supplémentaire, au-delà du 3e', br: 10.75, npc: false, poste: 'soins' },
  { code: 'HBMD081', label: 'Adjonction d\'un pilier d\'ancrage métallique à une prothèse dentaire plurale fixée [pilier de bridge]', br: 107.5, npc: false, poste: 'prothese' },
  { code: 'HBMD087', label: 'Adjonction d\'un pilier d\'ancrage céramométallique ou en équivalents minéraux à une prothèse dentaire plurale fixée [pilier de bridge] Maintenance', br: 107.5, npc: false, poste: 'prothese' },
  { code: 'HBMD016', label: 'Rescellement et/ou recollage d\'une ou deux couronnes ou ancrages d\'une prothèse dentaire fixée', br: null, npc: true, poste: 'prothese' },
  { code: 'HBMD009', label: 'Rescellement et/ou recollage de 3 couronnes ou ancrages, ou plus, d\'une prothèse dentaire fixée', br: null, npc: true, poste: 'prothese' },
  { code: 'HBGD027', label: 'Ablation d\'une prothèse dentaire scellée unitaire (couronne, facettes,inlay/onlay non métallique ; pour les prothèses sur implants, voir HBGD009)', br: null, npc: true, poste: 'soins' },
  { code: 'HBGD011', label: 'Ablation d\'un bloc métallique coulé ou d\'une prothèse dentaire à tenon radiculaire scellé (inlay onlay métallique, inlay core, bridge coulé, couronne', br: null, npc: true, poste: 'soins' },
  { code: 'HBGD005', label: 'Ablation d’un ancrage coronoradiculaire (vis et tenons métalliques ou fibre de verre, screw post)', br: null, npc: true, poste: 'soins' },
  { code: 'HBGD009', label: 'Ablation d\'une prothèse dentaire implantoportée (bridge, couronne, prothèse adjointe, attachements...) Bridge de base Inters supplémentaires Piliers P', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD364', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 1 à 3 dents', br: 64.5, npc: false, poste: 'prothese' },
  { code: 'HBLD476', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 4 dents', br: 75.25, npc: false, poste: 'prothese' },
  { code: 'HBLD224', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 5 dents', br: 86, npc: false, poste: 'prothese' },
  { code: 'HBLD371', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 6 dents', br: 96.75, npc: false, poste: 'prothese' },
  { code: 'HBLD123', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 7 dents', br: 107.5, npc: false, poste: 'prothese' },
  { code: 'HBLD270', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 8 dents', br: 118.25, npc: false, poste: 'prothese' },
  { code: 'HBLD148', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 9 dents', br: 129, npc: false, poste: 'prothese' },
  { code: 'HBLD231', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 10 dents', br: 139.75, npc: false, poste: 'prothese' },
  { code: 'HBLD215', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 11 dents', br: 150.5, npc: false, poste: 'prothese' },
  { code: 'HBLD262', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 12 dents', br: 161.25, npc: false, poste: 'prothese' },
  { code: 'HBLD232', label: 'Pose d\'une prothèse amovible de transition à plaque base résine, comportant 13 dents', br: 172, npc: false, poste: 'prothese' },
  { code: 'HBLD032', label: 'Pose d\'une prothèse amovible de transition complète unimaxillaire à plaque base résine Prothèses définitives résine', br: 182.75, npc: false, poste: 'prothese' },
  { code: 'HBLD101', label: 'Pose d\'une prothèse amovible définive à plaque base résine, comportant 9 dents', br: 129, npc: false, poste: 'prothese' },
  { code: 'HBLD138', label: 'Pose d\'une prothèse amovible définitive à plaque base résine, comportant 10 dents', br: 139.75, npc: false, poste: 'prothese' },
  { code: 'HBLD083', label: 'Pose d\'une prothèse amovible définitive à plaque base résine, comportant 11 dents', br: 150.5, npc: false, poste: 'prothese' },
  { code: 'HBLD370', label: 'Pose d\'une prothèse amovible définitive à plaque base résine, comportant 12 dents', br: 161.25, npc: false, poste: 'prothese' },
  { code: 'HBLD349', label: 'Pose d\'une prothèse amovible définitive à plaque base résine, comportant 13 dents', br: 172, npc: false, poste: 'prothese' },
  { code: 'HBLD031', label: 'Pose d\'une prothèse amovible définitive complète unimaxillaire à plaque base résine', br: 182.75, npc: false, poste: 'prothese' },
  { code: 'HBLD035', label: 'Pose d\'une prothèse amovible définitive complète bimaxillaire à plaque base résine Prothèses définitives à chassis métallique (stellite)', br: 365.5, npc: false, poste: 'prothese' },
  { code: 'HBLD131', label: '+30 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 1 à 3 dents', br: 193.5, npc: false, poste: 'prothese' },
  { code: 'HBLD332', label: '+35 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 4 dents', br: 204.25, npc: false, poste: 'prothese' },
  { code: 'HBLD452', label: '+40 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 5 dents', br: 215, npc: false, poste: 'prothese' },
  { code: 'HBLD474', label: '+45 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 6 dents', br: 225.75, npc: false, poste: 'prothese' },
  { code: 'HBLD075', label: '+50 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 7 dents', br: 236.5, npc: false, poste: 'prothese' },
  { code: 'HBLD470', label: '+55 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 8 dents', br: 247.25, npc: false, poste: 'prothese' },
  { code: 'HBLD435', label: '+60 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 9 dents', br: 258, npc: false, poste: 'prothese' },
  { code: 'HBLD079', label: '+65 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 10 dents', br: 268.75, npc: false, poste: 'prothese' },
  { code: 'HBLD203', label: '+70 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 11 dents', br: 279.5, npc: false, poste: 'prothese' },
  { code: 'HBLD112', label: '+75 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 12 dents', br: 290.25, npc: false, poste: 'prothese' },
  { code: 'HBLD308', label: '+80 Pose d\'une prothèse amovible définitive à châssis métallique, comportant 13 dents', br: 301, npc: false, poste: 'prothese' },
  { code: 'HBLD047', label: '+85 Pose d\'une prothèse amovible définitive complète unimaxillaire à châssis métallique', br: 311.75, npc: false, poste: 'prothese' },
  { code: 'HBLD046', label: '2*(SPR145) Pose d\'une prothèse amovible définitive complète bimaxillaire à châssis métallique', br: 623.5, npc: false, poste: 'prothese' },
  { code: 'HBLD048', label: '+85 Pose d\'une prothèse amovible définitive complète unimaxillaire à plaque base résine et d\'une prothèse amovible définitive complète unimaxillaire à', br: 494.5, npc: false, poste: 'implant' },
  { code: 'HBLD132', label: 'Pose d\'une prothèse amovible supra-implantaire à plaque résine comportant moins de 9 dents', br: 107.5, npc: false, poste: 'implant' },
  { code: 'HBLD492', label: 'Pose d\'une prothèse amovible supra-implantaire à plaque résine comportant de 9 à 13 dents', br: 150.5, npc: false, poste: 'implant' },
  { code: 'HBLD118', label: 'Pose d\'une prothèse amovible supra-implantaire complète unimaxillaire à plaque base résine', br: 182.75, npc: false, poste: 'implant' },
  { code: 'HBLD199', label: 'Pose d\'une prothèse amovible supra-implantaire complète bimaxillaire à plaque base résine', br: 365.5, npc: false, poste: 'implant' },
  { code: 'HBLD240', label: 'Pose d\'une prothèse amovible supra-implantaire à chassis métallique comportant moins de 9 dents', br: 236.5, npc: false, poste: 'implant' },
  { code: 'HBLD236', label: 'Pose d\'une prothèse amovible supra-implantaire à chassis métallique comportant de 9 à 13 dents', br: 279.5, npc: false, poste: 'implant' },
  { code: 'HBLD217', label: 'Pose d\'une prothèse amovible supra-implantaire complète unimaxillaire à chassis métallique', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD171', label: 'Pose d’une prothèse amovible supra-implantaire complète bimaxillaire à chassis métallique', br: 623.5, npc: false, poste: 'implant' },
  { code: 'HBLD030', label: 'Pose d\'une prothèse dentaire complète transvissée implantoportée Suppléments', br: 182.75, npc: false, poste: 'implant' },
  { code: 'HBLD008', label: 'Pose d\'un attachement coronoradiculaire sur une dent Dents contreplaquées sur prothèse résine', br: null, npc: true, poste: 'soins' },
  { code: 'YYYY176', label: 'Supplément pour pose d\'une dent contreplaquée sur une prothèse amovible à plaque base résine', br: 21.5, npc: false, poste: 'prothese' },
  { code: 'YYYY275', label: 'Supplément pour pose de 2 dents contreplaquées sur une prothèse amovible à plaque base résine', br: 43, npc: false, poste: 'prothese' },
  { code: 'YYYY246', label: 'Supplément pour pose de 3 dents contreplaquées sur une prothèse amovible à plaque base résine', br: 64.5, npc: false, poste: 'prothese' },
  { code: 'YYYY478', label: 'Supplément pour pose de 4 dents contreplaquées sur une prothèse amovible à plaque base résine', br: 86, npc: false, poste: 'prothese' },
  { code: 'YYYY426', label: 'Supplément pour pose de 5 dents contreplaquées sur une prothèse amovible à plaque base résine', br: 107.5, npc: false, poste: 'prothese' },
  { code: 'YYYY389', label: 'Supplément pour pose de 6 dents contreplaquées sur une prothèse amovible à plaque base résine Dents contreplaquées ou massives sur stellites', br: 129, npc: false, poste: 'prothese' },
  { code: 'YYYY159', label: 'Supplément pour pose d\'une dent contreplaquée ou massive sur une prothèse amovible sur châssis métallique', br: 32.25, npc: false, poste: 'prothese' },
  { code: 'YYYY329', label: 'Supplément pour pose de 2 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 64.5, npc: false, poste: 'prothese' },
  { code: 'YYYY258', label: 'Supplément pour pose de 3 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 96.75, npc: false, poste: 'prothese' },
  { code: 'YYYY259', label: 'Supplément pour pose de 4 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 129, npc: false, poste: 'prothese' },
  { code: 'YYYY440', label: 'Supplément pour pose de 5 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 161.25, npc: false, poste: 'prothese' },
  { code: 'YYYY447', label: 'Supplément pour pose de 6 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 193.5, npc: false, poste: 'prothese' },
  { code: 'YYYY142', label: 'Supplément pour pose de 7 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 225.75, npc: false, poste: 'prothese' },
  { code: 'YYYY158', label: 'Supplément pour pose de 8 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 258, npc: false, poste: 'prothese' },
  { code: 'YYYY476', label: 'Supplément pour pose de 9 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 290.25, npc: false, poste: 'prothese' },
  { code: 'YYYY079', label: 'Supplément pour pose de 10 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 322.5, npc: false, poste: 'prothese' },
  { code: 'YYYY184', label: 'Supplément pour pose de 11 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 354.75, npc: false, poste: 'prothese' },
  { code: 'YYYY284', label: 'Supplément pour pose de 12 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 387, npc: false, poste: 'prothese' },
  { code: 'YYYY236', label: 'Supplément pour pose de 13 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique', br: 419.25, npc: false, poste: 'prothese' },
  { code: 'YYYY353', label: 'Supplément pour pose de 14 dents contreplaquées ou massives sur une prothèse amovible à châssis métallique Adjonctions et Réparation de prothèse denta', br: 451.5, npc: false, poste: 'prothese' },
  { code: 'HBMD017', label: 'Adjonction ou changement de 1 élément d\'une prothèse dentaire amovible', br: 21.5, npc: false, poste: 'soins' },
  { code: 'HBMD114', label: 'Adjonction ou changement de 2 éléments d\'une prothèse dentaire amovible', br: 32.25, npc: false, poste: 'soins' },
  { code: 'HBMD322', label: 'Adjonction ou changement de 3 éléments d\'une prothèse dentaire amovible', br: 43, npc: false, poste: 'soins' },
  { code: 'HBMD404', label: 'Adjonction ou changement de 4 éléments d\'une prothèse dentaire amovible', br: 53.75, npc: false, poste: 'soins' },
  { code: 'HBMD245', label: 'Adjonction ou changement de 5 élément d\'une prothèse dentaire amovible', br: 64.5, npc: false, poste: 'soins' },
  { code: 'HBMD198', label: 'Adjonction ou changement de 6 éléments d\'une prothèse dentaire amovible', br: 75.25, npc: false, poste: 'soins' },
  { code: 'HBMD373', label: 'Adjonction ou changement de 7 élément d\'une prothèse dentaire amovible', br: 86, npc: false, poste: 'soins' },
  { code: 'HBMD228', label: 'Adjonction ou changement de 8 éléments d\'une prothèse dentaire amovible', br: 96.75, npc: false, poste: 'soins' },
  { code: 'HBMD286', label: 'Adjonction ou changement de 9 éléments d\'une prothèse dentaire amovible', br: 107.5, npc: false, poste: 'soins' },
  { code: 'HBMD329', label: 'Adjonction ou changement de 10 éléments d\'une prothèse dentaire amovible', br: 118.25, npc: false, poste: 'soins' },
  { code: 'HBMD226', label: 'Adjonction ou changement de 11 éléments d\'une prothèse dentaire amovible', br: 129, npc: false, poste: 'soins' },
  { code: 'HBMD387', label: 'Adjonction ou changement de 12 éléments d\'une prothèse dentaire amovible', br: 139.75, npc: false, poste: 'soins' },
  { code: 'HBMD134', label: 'Adjonction ou changement de 13 élément d\'une prothèse dentaire amovible', br: 150.5, npc: false, poste: 'soins' },
  { code: 'HBMD174', label: 'Adjonction ou changement de 14 éléments d\'une prothèse dentaire amovible Changement facette cosmétique', br: 161.25, npc: false, poste: 'esthetique' },
  { code: 'HBKD396', label: 'Changement de 1 facette d\'une prothèse dentaire amovible', br: 17.2, npc: false, poste: 'esthetique' },
  { code: 'HBKD431', label: 'Changement de 2 facettes d\'une prothèse dentaire amovible', br: 34.4, npc: false, poste: 'esthetique' },
  { code: 'HBKD300', label: 'Changement de 3 facettes d\'une prothèse dentaire amovible', br: 51.6, npc: false, poste: 'esthetique' },
  { code: 'HBKD212', label: 'Changement de 4 facettes d\'une prothèse dentaire amovible', br: 68.8, npc: false, poste: 'esthetique' },
  { code: 'HBKD462', label: 'Changement de 5 facettes d\'une prothèse dentaire amovible', br: 86, npc: false, poste: 'esthetique' },
  { code: 'HBKD213', label: 'Changement de 6 facettes d\'une prothèse dentaire amovible', br: 103.2, npc: false, poste: 'esthetique' },
  { code: 'HBKD140', label: 'Changement de 7 facettes d\'une prothèse dentaire amovible', br: 120.4, npc: false, poste: 'esthetique' },
  { code: 'HBKD244', label: 'Changement de 8 facettes d\'une prothèse dentaire amovible Attachements de prothèses supraimplantaire', br: 137.6, npc: false, poste: 'implant' },
  { code: 'HBKD005', label: 'Changement de dispositif d\'attachement d\'une prothèse dentaire amovible supra-implantaire', br: 32.25, npc: false, poste: 'implant' },
  { code: 'HBMD249', label: 'Adjonction ou changement de 1 élément soudé sur une prothèse dentaire amovible sur châssis métallique', br: 43, npc: false, poste: 'prothese' },
  { code: 'HBMD292', label: 'Adjonction ou changement de 2 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 86, npc: false, poste: 'prothese' },
  { code: 'HBMD188', label: 'Adjonction ou changement de 3 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 129, npc: false, poste: 'prothese' },
  { code: 'HBMD432', label: 'Adjonction ou changement de 4 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 172, npc: false, poste: 'prothese' },
  { code: 'HBMD283', label: 'Adjonction ou changement de 5 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 215, npc: false, poste: 'prothese' },
  { code: 'HBMD439', label: 'Adjonction ou changement de 6 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 258, npc: false, poste: 'prothese' },
  { code: 'HBMD425', label: 'Adjonction ou changement de 7 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 301, npc: false, poste: 'prothese' },
  { code: 'HBMD444', label: 'Adjonction ou changement de 8 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 344, npc: false, poste: 'prothese' },
  { code: 'HBMD485', label: 'Adjonction ou changement de 9 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 387, npc: false, poste: 'prothese' },
  { code: 'HBMD410', label: 'Adjonction ou changement de 10 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 430, npc: false, poste: 'prothese' },
  { code: 'HBMD429', label: 'Adjonction ou changement de 11 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 473, npc: false, poste: 'prothese' },
  { code: 'HBMD281', label: 'Adjonction ou changement de 12 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 516, npc: false, poste: 'prothese' },
  { code: 'HBMD200', label: 'Adjonction ou changement de 13 éléments soudés sur une prothèse dentaire amovible sur châssis métallique', br: 559, npc: false, poste: 'prothese' },
  { code: 'HBMD298', label: 'Adjonction ou changement de 14 éléments soudés sur une prothèse dentaire amovible sur châssis métallique Réparations de la prothèse', br: 602, npc: false, poste: 'prothese' },
  { code: 'HBMD020', label: 'Réparation d\'une prothèse dentaire amovible en résine, fêlée ou fracturée', br: 21.5, npc: false, poste: 'prothese' },
  { code: 'HBMD008', label: 'Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, sans démontage d\'éléments', br: 32.25, npc: false, poste: 'prothese' },
  { code: 'HBMD002', label: '+3 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 1 élément', br: 38.7, npc: false, poste: 'prothese' },
  { code: 'HBMD488', label: '+6 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 2 éléments', br: 45.15, npc: false, poste: 'prothese' },
  { code: 'HBMD469', label: '+9 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 3 éléments', br: 51.6, npc: false, poste: 'prothese' },
  { code: 'HBMD110', label: '+12 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 4 éléments', br: 58.05, npc: false, poste: 'prothese' },
  { code: 'HBMD349', label: '+15 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 5 éléments', br: 64.5, npc: false, poste: 'prothese' },
  { code: 'HBMD386', label: '+18 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 6 éléments', br: 70.95, npc: false, poste: 'prothese' },
  { code: 'HBMD339', label: '+21 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 7 éléments', br: 77.4, npc: false, poste: 'prothese' },
  { code: 'HBMD459', label: '+24 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 8 éléments', br: 83.85, npc: false, poste: 'prothese' },
  { code: 'HBMD438', label: '+27 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 9 éléments', br: 90.3, npc: false, poste: 'prothese' },
  { code: 'HBMD481', label: '+30 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 10 éléments', br: 96.75, npc: false, poste: 'prothese' },
  { code: 'HBMD449', label: '+33 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 11 éléments', br: 103.2, npc: false, poste: 'prothese' },
  { code: 'HBMD312', label: '+36 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 12 éléments', br: 109.65, npc: false, poste: 'prothese' },
  { code: 'HBMD289', label: '+39 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 13 éléments', br: 116.1, npc: false, poste: 'prothese' },
  { code: 'HBMD400', label: '+42 Réparation d\'une fracture de châssis métallique de prothèse dentaire amovible, avec remontage de 14 éléments', br: 122.55, npc: false, poste: 'prothese' },
  { code: 'HBMD019', label: 'DC9 Révision des piliers implantoportés d\'une prothèse dentaire', br: null, npc: true, poste: 'implant' },
  { code: 'HBMD076', label: 'Réparation de l\'artifice cosmétique d\'une dent prothétique par technique directe', br: null, npc: true, poste: 'prothese' },
  { code: 'HBMD079', label: 'Réparation de l\'artifice cosmétique d\'une dent prothétique par technique indirecte', br: null, npc: true, poste: 'prothese' },
  { code: 'HBMD007', label: 'Réfection des bords et/ou de l\'intrados d\'une prothèse dentaire amovible partielle', br: null, npc: true, poste: 'soins' },
  { code: 'HBMD004', label: 'Réfection de la base d\'une prothèse dentaire amovible complète Parodontologie Par secteur dentaire, on entend la portion de l\'arcade dentaire correspo', br: null, npc: true, poste: 'implant' },
  { code: 'HBQD001', label: 'Bilan parodontal Exploration du parodonte par sondage, étude de l\'indice de plaque', br: null, npc: true, poste: 'paro' },
  { code: 'HBLD052', label: 'Pose d’un dispositif unimaxillaire de contention extracoronaire par attelle composite collée, sur 1 à 6 dents', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD050', label: 'Pose d’un dispositif unimaxillaire de contention extracoronaire par attelle composite collée, sur 7 dents ou plus', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD053', label: 'Pose d’un dispositif unimaxillaire de contention extracoronaire par attelle métallique coulée et collée, sur 1 à 6 dents', br: 96.4, npc: false, poste: 'soins' },
  { code: 'HBLD051', label: 'Pose d’un dispositif unimaxillaire de contention extracoronaire par attelle métallique coulée et collée, sur 7 dents ou plus', br: 96.4, npc: false, poste: 'soins' },
  { code: 'LBGD001', label: 'Ablation de moyen de contention maxillaire et/ou mandibulaire intrabuccal Ablation de ligature d\'Ivy, d\'arc vestibulaire... Curetage périapical dentai', br: null, npc: true, poste: 'soins' },
  { code: 'HBGB001', label: 'Curetage d\'alvéole dentaire Hors acte d\'avulsion dentaire', br: null, npc: true, poste: 'soins' },
  { code: 'HBGB005', label: 'DC24 Curetage périapical avec résection de l\'apex d\'une racine dentaire endodontiquement traitée', br: 50.16, npc: false, poste: 'soins' },
  { code: 'HBGB003', label: 'DC24+SC14 Curetage périapical avec résection de l\'apex et obturation radiculaire rétrograde d\'une incisive ou d\'une canine', br: 83.9, npc: false, poste: 'soins' },
  { code: 'HBGB002', label: 'DC24+SC20 Curetage périapical avec résection de l\'apex et obturation radiculaire rétrograde d\'une prémolaire', br: 98.36, npc: false, poste: 'soins' },
  { code: 'HBGB004', label: 'DC24+SC34 Curetage périapical avec résection de l\'apex et obturation radiculaire rétrograde d\'une molaire', br: 132.1, npc: false, poste: 'soins' },
  { code: 'HBFA006', label: 'Gingivectomie sur un secteur de 1 à 3 dents', br: null, npc: true, poste: 'paro' },
  { code: 'HBFA007', label: 'DC20 Gingivectomie sur un secteur de 4 à 6 dents', br: 41.8, npc: false, poste: 'paro' },
  { code: 'HBFA008', label: 'Gingivectomie sur un secteur de 7 dents ou plus', br: null, npc: true, poste: 'paro' },
  { code: 'HBAA338', label: 'Allongement coronaire par gingivectomie sur une dent', br: null, npc: true, poste: 'paro' },
  { code: 'HBFA005', label: 'Ostéoplastie soustractive de l\'arcade alvéolaire sur un secteur de 1 à 3 dents', br: null, npc: true, poste: 'soins' },
  { code: 'HBFA004', label: 'Ostéoplastie soustractive de l\'arcade alvéolaire sur un secteur de 4 à 6 dents', br: null, npc: true, poste: 'soins' },
  { code: 'HBFA003', label: 'Ostéoplastie soustractive de l\'arcade alvéolaire sur un secteur de 7 dents ou plus', br: null, npc: true, poste: 'soins' },
  { code: 'HBFA013', label: 'Exérèse d\'hypertrophie gingivale ou de crête flottante localisée', br: null, npc: true, poste: 'paro' },
  { code: 'HBFA012', label: 'Exérèse d\'hypertrophie gingivale ou de crête flottante sur une arcade maxillaire ou mandibulaire complète', br: null, npc: true, poste: 'paro' },
  { code: 'LBFA031', label: 'Résection d\'hypertrophie osseuse intrabuccale Actes thérapeutiques sur le parodonte par addition', br: 34.55, npc: false, poste: 'soins' },
  { code: 'HBMA004', label: 'Régénération parodontale sur un sextant Pose de membrane de régénération tissulaire parodontale Comblement de perte de substance de l\'arcade alvéolair', br: null, npc: true, poste: 'paro' },
  { code: 'HBED023', label: 'Greffe épithélioconjonctive ou conjonctive sur la gencive, sur un secteur de 1 à 3 dents', br: null, npc: true, poste: 'implant' },
  { code: 'HBED024', label: 'Greffe épithélioconjonctive ou conjonctive sur la gencive, sur un sextant', br: null, npc: true, poste: 'implant' },
  { code: 'HBMA006', label: 'Ostéoplastie d\'une alvéole dentaire avec comblement par biomatériau', br: null, npc: true, poste: 'soins' },
  { code: 'HBMA003', label: 'Ostéoplastie d\'une alvéole dentaire avec comblement par autogreffe osseuse', br: null, npc: true, poste: 'soins' },
  { code: 'HBBA003', label: 'DC41 Ostéoplastie additive de l\'arcade alvéolaire sur un secteur de 1 à 3 dents (augmentations osseuses)', br: null, npc: true, poste: 'implant' },
  { code: 'HBBA002', label: 'DC129 Ostéoplastie additive de l\'arcade alvéolaire sur un secteur de 4 à 6 dents', br: null, npc: true, poste: 'implant' },
  { code: 'HBBA004', label: 'DC143 Ostéoplastie additive de l\'arcade alvéolaire sur un secteur de 7 dents ou plus', br: null, npc: true, poste: 'implant' },
  { code: 'HBJB001', label: 'Évacuation d\'abcès parodontal', br: 40, npc: false, poste: 'paro' },
  { code: 'HBGB006', label: 'Surfaçage radiculaire dentaire sur un sextant', br: null, npc: true, poste: 'paro' },
  { code: 'HBJA003', label: 'Assainissement parodontal par lambeau sur un sextant', br: null, npc: true, poste: 'paro' },
  { code: 'HBMA001', label: 'DC36 Plastie mucogingivale par lambeau déplacé latéralement, coronairement ou apicalement', br: null, npc: true, poste: 'implant' },
  { code: 'HBMD018', label: 'Séance de préparation (mise sous condition) tissulaire des surfaces d\'appui muqueux d\'une prothèse dentaire, sur une arcade', br: null, npc: true, poste: 'implant' },
  { code: 'HAPD001', label: 'DC10 Section de bride muqueuse ou de frein intrabuccal Section et désinsertion interincisive de frein labial supérieur Section de frein de la langue', br: 20.9, npc: false, poste: 'soins' },
  { code: 'HAPA001', label: 'DC14 Section de bride muqueuse ou de frein intrabuccal avec plastie par lambeau local', br: 29.34, npc: false, poste: 'paro' },
  { code: 'HAPA003', label: 'DC10 Libération musculaire et muqueuse d\'une ankyloglossie Implantologie Chirurgie', br: 62.7, npc: false, poste: 'implant' },
  { code: 'GBBA002', label: 'Comblement préimplantaire sous muqueux du sinus maxillaire Cet acte n\'est actuellement pas accessible dans la CCAM ambulatoire version 34.', br: null, npc: true, poste: 'implant' },
  { code: 'LABA002', label: 'Désépaississement des tissus de recouvrement d\'un site implantaire (gencive, peau...) Chez l\'enfant Les actes d\'implantologie chez l\'enfant sont pris', br: 41.8, npc: false, poste: 'implant' },
  { code: 'LBLD075', label: 'Pose d\'1 implant intra-osseux intra-buccal, chez l\'enfant', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD066', label: 'Pose de 2 implants intra-osseux intra-buccaux, chez l\'enfant', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD281', label: 'Pose de 3 implants intra-osseux intra-buccaux, chez l\'enfant', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD117', label: 'Pose de 4 implants intra-osseux intra-buccaux, chez l\'enfant Dégagement et activation chez l\'enfant (mise en place d\'un moignon transmuqueux ou transc', br: null, npc: true, poste: 'implant' },
  { code: 'LAPB451', label: 'Dégagement et activation de 1 implant intra-osseux intrabuccal, chez l\'enfant', br: null, npc: false, poste: 'implant' },
  { code: 'LBLD311', label: 'Dégagement et activation de 2 implants intra-osseux intrabuccaux, chez l\'enfant', br: null, npc: false, poste: 'implant' },
  { code: 'LAPB459', label: 'Dégagement et activation de 3 implants intra-osseux intrabuccaux, chez l\'enfant', br: null, npc: false, poste: 'implant' },
  { code: 'LBLD408', label: 'Dégagement et activation de 4 implants intra-osseux intrabuccaux, chez l\'enfant Ablation d\'implants chez l\'enfant', br: null, npc: false, poste: 'soins' },
  { code: 'LBGA280', label: 'Ablation de 1 implant intra-osseux intrabuccal avec réssection osseuse chez l\'enfant', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA441', label: 'Ablation de 2 implants intra-osseux intrabuccaux avec réssection osseuse chez l\'enfant', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA354', label: 'Ablation de 3 implants intra-osseux intrabuccaux avec réssection osseuse chez l\'enfant', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA049', label: 'Ablation de 4 implants intra-osseux intrabuccaux avec réssection osseuse chez l\'enfant', br: null, npc: true, poste: 'soins' },
  { code: 'LBLD015', label: 'Pose d\'1 implant intra-osseux intra-buccal, chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD010', label: 'Pose de 2 implants intra-osseux intra-buccaux, chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD013', label: 'Pose de 3 implants intra-osseux intra-buccal, chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD004', label: 'Pose de 4 implants intra-osseux intra-buccaux, chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD020', label: 'Pose de 5 implants intra-osseux intra-buccal, chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD025', label: 'Pose de 6 implants intra-osseux intra-buccaux, chez l\'adulte Dégagement et activation chez l\'adulte (mise en place d\'un moignon transmuqueux ou transc', br: null, npc: true, poste: 'implant' },
  { code: 'LAPB002', label: 'Dégagement et activation de 1 implant intra-osseux intrabuccal chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LAPB004', label: 'Dégagement et activation de 2 implants intra-osseux intrabuccaux chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LAPB003', label: 'Dégagement et activation de 3 implants intra-osseux intrabuccaux chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LAPB001', label: 'Dégagement et activation de 4 implants intra-osseux intrabuccaux chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LAPB005', label: 'Dégagement et activation de 5 implants intra-osseux intrabuccaux chez l\'adulte', br: null, npc: true, poste: 'implant' },
  { code: 'LAPB006', label: 'Dégagement et activation de 6 implants intra-osseux intrabuccaux chez l\'adulte Ablation d\'implants chez l\'adulte', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA004', label: 'Ablation de 1 implant intra-osseux intrabuccal avec réssection osseuse chez l\'adulte', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA003', label: 'Ablation de 2 implants intra-osseux intrabuccaux avec réssection osseuse chez l\'adulte', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA002', label: 'Ablation de 3 implants intra-osseux intrabuccaux avec réssection osseuse chez l\'adulte', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA006', label: 'Ablation de 4 implants intra-osseux intrabuccaux avec réssection osseuse chez l\'adulte', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA007', label: 'Ablation de 5 implants intra-osseux intrabuccaux avec réssection osseuse chez l\'adulte', br: null, npc: true, poste: 'soins' },
  { code: 'LBGA008', label: 'Ablation de 6 implants intra-osseux intrabuccaux avec réssection osseuse chez l\'adulte', br: null, npc: true, poste: 'soins' },
  { code: 'HBLD012', label: 'Pose d\'une infrastructure coronaire sur 1 implant (inlay core sur implant)', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD017', label: 'Pose d\'infrastructure coronaire sur 2 implants', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD021', label: 'Pose d\'infrastructure coronaire sur 3 implants', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD013', label: 'Pose d\'infrastructure coronaire sur 4 implants', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD005', label: 'Pose d\'infrastructure coronaire sur 5 implants ou plus Moyens de liaison (locator, barre Ackerman...)', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD019', label: 'Pose de moyen de liaison sur 1 implant préprothétique intra-osseux, intra-buccal (sauf barre de conjonction)', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD073', label: 'Pose de moyen de liaison sur 2 implants préprothétiques intra-osseux intra-buccaux', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD086', label: 'Pose de moyen de liaison sur 3 implanst préprothétiques intra-osseux, intra-buccaux', br: null, npc: true, poste: 'soins' },
  { code: 'LBLD193', label: 'Pose de moyen de liaison sur 4 implants préprothétiques intra-osseux intra-buccaux', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD447', label: 'Pose de moyen de liaison sur 5 implanst préprothétiques intra-osseux, intra-buccaux', br: null, npc: true, poste: 'soins' },
  { code: 'LBLD270', label: 'Pose de moyen de liaison sur 6 implants préprothétiques intra-osseux intra-buccaux', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD034', label: 'Pose de barre de conjonction entre 2 implants intra-buccaux', br: null, npc: true, poste: 'implant' },
  { code: 'LBLD057', label: 'Pose de barre de conjonction entre 3 implants intra-buccaux ou plus Guides', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD057', label: 'Pose d\'une plaque base résine pour guide radiologique préimplantaire dentaire, pour 1 arcade', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD078', label: 'Pose d\'une plaque base résine pour guide radiologique préimplantaire dentaire, pour 2 arcades', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD056', label: 'Pose d\'une plaque base résine pour guide chirurgical préimplantaire dentaire, pour 1 arcade', br: null, npc: true, poste: 'implant' },
  { code: 'HBLD084', label: 'Pose d\'une plaque base résine pour guide chirurgical préimplantaire dentaire, pour 2 arcades', br: null, npc: true, poste: 'implant' },
  { code: 'HBMP001', label: 'Transformation d\'un guide radiologique préimplantaire en guide chirurgical Implants craniens/faciaux', br: null, npc: true, poste: 'implant' },
  { code: 'LALA002', label: 'Pose d\'1 implant intra-osseux cranien ou facial pour fixation d\'épithèse ou d\'appareillage auditif ostéointégré', br: 167.2, npc: false, poste: 'implant' },
  { code: 'LALA001', label: 'Pose de plusieurs implants intra-osseux crânienset/ou faciaux pour fixation d\'épithèse', br: 250.8, npc: false, poste: 'implant' },
  { code: 'LALB001', label: 'Pose de moyen de liaison sur implants crâniens et/ou faciaux Bilans', br: 115.2, npc: false, poste: 'implant' },
  { code: 'ZAQP001', label: 'Photographies de la face', br: null, npc: true, poste: 'soins' },
  { code: 'ADQB001', label: 'Électromyographie de détection du muscle ptérygoïdien latéral, par électrode aiguille', br: 42.08, npc: false, poste: 'soins' },
  { code: 'HDQP002', label: 'Exploration du flux aérien bucco-naso-pharyngé par débitmétrie, pour étude de la fonction vélopalatine', br: null, npc: false, poste: 'soins' },
  { code: 'LBQP002', label: 'Enregistrement électronique des mouvements de la mandibule', br: null, npc: false, poste: 'soins' },
  { code: 'HAHD001', label: 'Frottis et/ou prélèvement intrabuccal', br: 10.2, npc: false, poste: 'soins' },
  { code: 'HAHA002', label: 'Biopsie de lèvre (peut être facturé avec une consultation, avec modificateur 2)', br: 20.97, npc: false, poste: 'soins' },
  { code: 'HAHD003', label: 'Biopsie de la cavité orale et/ou de l\'oropharynx, sans coloration vitale', br: 19.67, npc: false, poste: 'soins' },
  { code: 'HAHD002', label: 'Biopsie de la cavité orale et/ou de l\'oropharynx, avec guidage par des colorations vitales', br: 23.24, npc: false, poste: 'soins' },
  { code: 'HCHA001', label: 'Biopsie de glande salivaire majeure [principale]', br: 29.49, npc: false, poste: 'soins' },
  { code: 'HCHA002', label: 'Biopsie des petites glandes salivaires [glandes salivaires mineures] [glandes salivaires accessoires]', br: 23.68, npc: false, poste: 'soins' },
  { code: 'HCHB001', label: 'Ponction ou cytoponction de glande salivaire, par voie transcutanée Chirurgie maxilo-faciale', br: 28.15, npc: false, poste: 'soins' },
  { code: 'ADPA004', label: 'Décompression du nerf alvéolaire inférieur [dentaire inférieur], par abord intrabuccal', br: 121.62, npc: false, poste: 'soins' },
  { code: 'ADCA004', label: 'Déroutement du nerf alvéolaire inférieur [dentaire inférieur], par abord intrabuccal', br: 104.5, npc: false, poste: 'soins' },
  { code: 'GBPA004', label: 'Sinusotomie maxillaire, par abord de la fosse canine [abord vestibulaire]', br: 167.2, npc: false, poste: 'soins' },
  { code: 'HAPA004', label: 'Marsupialisation d\'un kyste du plancher de la bouche', br: 54.16, npc: false, poste: 'soins' },
  { code: 'HAMA001', label: 'Glossoplastie de réduction', br: 125.4, npc: false, poste: 'soins' },
  { code: 'HADA001', label: 'Labioglossopexie', br: 141.99, npc: false, poste: 'soins' },
  { code: 'HAMA026', label: 'Pelviglossoplastie', br: 154.49, npc: false, poste: 'soins' },
  { code: 'HADA002', label: 'Hyomandibulopexie', br: 153.15, npc: false, poste: 'soins' },
  { code: 'HAAA002', label: 'Approfondissement du vestibule oral [sillon gingivojugal] par section mucopériostée', br: 83.6, npc: false, poste: 'paro' },
  { code: 'HAAA001', label: 'Approfondissement du vestibule oral [sillon gingivojugal] par section mucopériostée avec greffe cutanée ou muqueuse', br: 104.61, npc: false, poste: 'paro' },
  { code: 'HAAA003', label: 'Approfondissement du plancher de la bouche par section musculaire', br: 125.4, npc: false, poste: 'soins' },
  { code: 'HDAA002', label: 'Véloplastie d\'allongement avec lambeau palatin', br: 233.38, npc: false, poste: 'paro' },
  { code: 'HDMA010', label: 'Véloplastie secondaire intravélaire', br: 233.38, npc: false, poste: 'soins' },
  { code: 'HAFA022', label: 'Exérèse transfixiante de lésion de la joue, par abord facial', br: 125.4, npc: false, poste: 'soins' },
  { code: 'LCGA002', label: 'Ablation de corps étranger projeté dans les tissus mous buccofaciaux, par abord intrabuccal', br: 63.61, npc: false, poste: 'soins' },
  { code: 'HCLD001', label: 'Cathétérisme de canal salivaire sans sialographie', br: 37.55, npc: false, poste: 'soins' },
  { code: 'LBLB002', label: 'Infiltration périarticulaire temporomandibulaire, par voie transcutanée', br: 13.9, npc: false, poste: 'soins' },
  { code: 'LBLB001', label: 'Infiltration et/ou lavage de l\'articulation temporomandibulaire, par voie transcutanée Prothèse maxilo-faciale', br: 22.94, npc: false, poste: 'soins' },
  { code: 'LBLD012', label: 'Pose de dispositif intrabuccal d\'expansion tissulaire pour rehaussement de crête alvéolaire', br: null, npc: true, poste: 'soins' },
  { code: 'HALD001', label: 'Pose de dispositif intrabuccal d\'expansion labiojugale', br: 153.6, npc: false, poste: 'soins' },
  { code: 'HALD005', label: 'Pose d\'une prothèse intrabuccale pour perte de substance du palais dur et du palais mou', br: 192, npc: false, poste: 'soins' },
  { code: 'LBEP005', label: 'Réduction orthopédique d\'une luxation temporomandibulaire unilatérale ou bilatérale', br: 15.49, npc: false, poste: 'soins' },
  { code: 'LBLD016', label: 'Pose d\'un appareillage obturateur pour perte de substance maxillaire, chez un patient denté', br: 112.19, npc: false, poste: 'soins' },
  { code: 'LBLD023', label: 'Pose d\'un appareillage obturateur pour perte de substance maxillaire, chez un patient édenté total', br: 185.66, npc: false, poste: 'soins' },
  { code: 'LBLA001', label: 'Pose d\'une prothèse obturatrice à étage ou d\'une balle obturatrice souple après résection de l\'os maxillaire', br: 288, npc: false, poste: 'soins' },
  { code: 'LBLD002', label: 'Pose d\'un appareillage de mobilisation en latéralité et/ou en propulsion pour fracture unicondylaire ou bicondylaire de la mandibule', br: 153.6, npc: false, poste: 'soins' },
  { code: 'LBLD008', label: 'Pose d\'un appareillage de mobilisation mandibulaire en rotation pure', br: 153.6, npc: false, poste: 'soins' },
  { code: 'LBLD005', label: 'Pose d\'un appareillage de mobilisation mandibulaire en rotation et en propulsion', br: 153.6, npc: false, poste: 'soins' },
  { code: 'LBLD021', label: 'Pose d\'un appareillage actif pur de rééducation de la cinétique mandibulaire', br: 153.6, npc: false, poste: 'soins' },
  { code: 'QALP001', label: 'Pose d\'un appareillage de compression pour prévention et/ou correction de cicatrices vicieuses cervicofaciales', br: 153.6, npc: false, poste: 'soins' },
  { code: 'ZAMP001', label: 'Confection d\'un moulage facial', br: 48.21, npc: false, poste: 'soins' },
  { code: 'ZALP001', label: 'Pose d\'une prothèse souple utilisant les contredépouilles naturelles pour ancrage de prothèse faciale', br: 200.13, npc: false, poste: 'soins' },
  { code: 'ZALP002', label: 'Pose d\'une épithèse faciale plurirégionale', br: null, npc: true, poste: 'soins' },
  { code: 'LBLD001', label: 'Pose d\'un châssis métallique support de prothèse maxillofaciale [prothèse obturatrice]', br: 129, npc: false, poste: 'prothese' },
  { code: 'YYYY059', label: 'Appareillage de contention ou de réduction pré et postopératoire pour résection ou greffe du maxillaire ou de la mandibule', br: 249.6, npc: false, poste: 'soins' },
]

const BY_CODE = new Map(CCAM_ACTES.map((a) => [a.code.toUpperCase(), a]))
/** Normalise un code CCAM (4 lettres + 3 chiffres) ou null. */
function normCcam(code?: string | null): string | null {
  if (!code) return null
  const m = code.toUpperCase().match(/[A-Z]{4}\d{3}/)
  return m ? m[0] : null
}
/** Recherche un acte CCAM par code exact (insensible à la casse). */
export function ccamFind(code?: string | null): CcamActe | undefined {
  const m = normCcam(code)
  return m ? BY_CODE.get(m) : undefined
}

/**
 * Poste déduit du PRÉFIXE CCAM — filet de sécurité pour qu'AUCUN code (même hors liste, HN ou futur)
 * ne reste sans rattachement. Fondé sur la hiérarchie de la CCAM bucco-dentaire (chapitre 07 + maxillofacial).
 */
export function posteFromPrefix(code?: string | null): CcamPoste {
  const c = normCcam(code)
  if (!c) return 'soins'
  const p4 = c.slice(0, 4)
  // Implantologie : pose/dégagement/liaison/barre/ablation d'implants (L*LD/L*PB/L*GA/L*LA…)
  if (/^LBLD|^LBPB|^LAPB|^LBGA|^LBLA|^LALA|^LALB|^LABA/.test(c)) return 'implant'
  // Prothèses fixes (couronnes, bridges, inlay-core, amovibles, stellites) : HBLD###
  if (p4 === 'HBLD') return 'prothese'
  // Parodontologie / gingival / surfaçage / assainissement / greffe gingivale
  if (/^HBJA|^HBGB|^HBFA|^HBAA|^HBMA|^HBJB|^HBBA|^HAAA|^HDAA|^HBED02/.test(c)) return 'paro'
  // Orthopédie dento-faciale / téléradio ortho
  if (/^TA|^TO|^HBPD|^HBPA/.test(c)) return 'ortho'
  // Esthétique (éclaircissement, facettes cosmétiques, changement de facettes)
  if (/^HBKD/.test(c)) return 'esthetique'
  // Soins, endodontie, chirurgie, radio, restaurations, divers → soins
  return 'soins'
}

/** Base de remboursement Sécu pour un code CCAM (null si non prise en charge ou inconnu). */
export function ccamBR(code?: string | null): number | null {
  return ccamFind(code)?.br ?? null
}
/**
 * Poste de garantie associé à un code CCAM : liste officielle d'abord, sinon déduction par PRÉFIXE.
 * Ainsi tout code présent sur un devis est toujours classé (aucun oubli).
 */
export function ccamPoste(code?: string | null): CcamPoste | undefined {
  if (!code) return undefined
  return ccamFind(code)?.poste ?? posteFromPrefix(code)
}
/** true si le code est dans la liste officielle embarquée. */
export function isKnownCcam(code?: string | null): boolean {
  return !!ccamFind(code)
}
/** Libellé officiel d un code CCAM. */
export function ccamLabel(code?: string | null): string | undefined {
  return ccamFind(code)?.label
}
